'use client';

import React, { useEffect } from 'react';
import { useBotStore } from '../store/useBotStore';
import { useI18nStore } from '../store/useI18nStore';
import { formatToLocalTime } from '../utils/timezone';
import { Download, Shield } from 'lucide-react';
import * as XLSX from 'xlsx';

export default function AuditTrailView() {
  const { dbAuditLogs, fetchDbAuditLogs, auditLogs, user } = useBotStore();
  const t = useI18nStore((state) => state.t);

  useEffect(() => {
    fetchDbAuditLogs();
  }, [fetchDbAuditLogs]);

  // Merge DB logs and local simulated logs
  const displayLogs = dbAuditLogs && dbAuditLogs.length > 0 
    ? dbAuditLogs.map(log => ({
        id: log.id,
        timestamp: log.createdAt || log.timestamp,
        action: log.action,
        ipAddress: log.ipAddress,
        status: log.status
      }))
    : auditLogs;

  const handleExportAuditExcel = () => {
    if (!user) return;

    // 1. Define compliance report headers & metadata
    const reportMetadata = [
      [`${useBotStore.getState().appConfig?.appName?.toUpperCase() || 'FOREX BOT AI'} - REGULATORY COMPLIANCE AUDIT REPORT`],
      ['BAPPEBTI / GLOBAL REGULATORY COMPLIANCE COMPLIANT'],
      [],
      ['Report Generated By:', user.email],
      ['Report Date:', new Date().toLocaleString()],
      ['Total Logged Actions:', displayLogs.length.toString()],
      [],
      [t('audit.colId'), t('audit.colTimestamp'), t('audit.colAction'), t('audit.colIp'), t('audit.colStatus')]
    ];

    // 2. Map audit logs to rows
    const logRows = displayLogs.map((log) => [
      log.id,
      formatToLocalTime(log.timestamp),
      log.action,
      log.ipAddress,
      log.status
    ]);

    // 3. Add signature section at the bottom
    const signatureSection = [
      [],
      [],
      ['AUDITED & VERIFIED BY:'],
      [],
      [],
      ['_______________________________', '_______________________________'],
      ['Compliance Officer Signature', 'Internal IT Auditor Signature'],
      [`Date: ${new Date().toLocaleDateString()}`, `Date: ${new Date().toLocaleString()}`]
    ];

    // Combine all sections into a single worksheet
    const fullData = [...reportMetadata, ...logRows, ...signatureSection];
    
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(fullData);

    // Style column widths for readability
    ws['!cols'] = [
      { wch: 15 }, // Log ID
      { wch: 25 }, // Timestamp
      { wch: 45 }, // Action
      { wch: 20 }, // IP
      { wch: 15 }, // Status
      { wch: 30 }  // Signatures
    ];

    XLSX.utils.book_append_sheet(wb, ws, 'Compliance Audit Trail');
    
    // Trigger download
    XLSX.writeFile(wb, `Audit_Trail_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  return (
    <div className="space-y-6 animate-scale-up">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold text-slate-100 font-mono flex items-center gap-2.5">
            <Shield className="w-6 h-6 text-cyan-400" />
            {t('audit.title')}
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            {t('audit.desc')}
          </p>
        </div>
        <button
          onClick={handleExportAuditExcel}
          className="px-4 py-2 bg-slate-900 hover:bg-slate-850 text-slate-200 hover:text-cyan-455 border border-slate-800 rounded-xl text-xs font-bold font-mono transition-all duration-300 flex items-center gap-1.5 active:scale-95 shadow-md"
        >
          <Download className="w-4 h-4" />
          {t('audit.export')}
        </button>
      </div>

      {/* Audit Logs Table */}
      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-850 text-[10px] font-mono text-slate-550 uppercase tracking-wider">
                <th className="py-3 px-4 font-normal">{t('audit.colId')}</th>
                <th className="py-3 px-4 font-normal">{t('audit.colTimestamp')}</th>
                <th className="py-3 px-4 font-normal">{t('audit.colAction')}</th>
                <th className="py-3 px-4 font-normal">{t('audit.colIp')}</th>
                <th className="py-3 px-4 text-right font-normal">{t('audit.colStatus')}</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-850/40 text-xs font-mono text-slate-350">
              {displayLogs.map((log) => (
                <tr key={log.id} className="hover:bg-slate-955/20 transition-colors duration-250">
                  <td className="py-3.5 px-4 text-slate-200 font-semibold">{log.id.substring(0, 8)}...</td>
                  <td className="py-3.5 px-4 text-slate-550">{formatToLocalTime(log.timestamp)}</td>
                  <td className="py-3.5 px-4 font-semibold text-slate-300">{log.action}</td>
                  <td className="py-3.5 px-4 text-slate-450">{log.ipAddress}</td>
                  <td className="py-3.5 px-4 text-right">
                    <span className={`px-2 py-0.5 text-[9px] font-bold rounded ${
                      log.status === 'SUCCESS' 
                        ? 'bg-emerald-950 text-emerald-400 border border-emerald-900/35' 
                        : 'bg-rose-950 text-rose-400 border border-rose-900/35'
                    }`}>
                      {log.status}
                    </span>
                  </td>
                </tr>
              ))}
              {displayLogs.length === 0 && (
                <tr>
                  <td colSpan={5} className="py-8 text-center text-slate-500">
                    {t('audit.empty')}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
